### ISSUE TITLE
Realign testimonial

### ISSUE THREAD

**Issue by paragasu** [phisoft/wongandsimdental-web#13]
mobile
![image](https://user-images.githubusercontent.com/27353/84850916-82d28980-b08b-11ea-8e7b-8eb4380110e4.png)
![image](https://user-images.githubusercontent.com/27353/84850923-89610100-b08b-11ea-84e7-75d541d986ab.png)

website
![image](https://user-images.githubusercontent.com/27353/84850903-764e3100-b08b-11ea-95a5-04bb5e5f7efe.png)

**Comment by izahshahirah** [comment]
#19 done
