### ISSUE TITLE
Update our teams

### ISSUE THREAD

**Issue by paragasu** [phisoft/wongandsimdental-web#71]
[13:25, 03/04/2022] Kenneth: can add this dr in wong & sim dental team
[13:25, 03/04/2022] Kenneth: above dr ha kien oon
[13:25, 03/04/2022] Kenneth: Dr Charlotte Hing
Associate Dentist (Pulau Tikus)
BDS (PIDC)

Focus: 
General Dentistry, Preventative Dentistry, Root Canal Treatment, Wisdom Tooth Surgery, Microscopic Dentistry, Fixed & Removable Dental Prosthesis, Children Dentistry.

**Comment by russel0907** [comment]
Add and update new user section according to client's request ;

![Screenshot (227)](https://user-images.githubusercontent.com/94702093/161492251-fb1d4565-c214-4dc5-b0da-a5a6a7661ee2.png)
