### ISSUE TITLE
Update dr charlotte photo

### ISSUE THREAD

**Issue by paragasu** [phisoft/wongandsimdental-web#74]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/173018625-654b911a-a92d-4752-b1fb-7664ca6db7a2.png">

**Comment by russel0907** [comment]
1. Update Photo
2. Optimize Photo Size and resolution

## View
![Screenshot (362)](https://user-images.githubusercontent.com/94702093/173031470-d579836d-7caa-4618-9016-9c4d0e5e2ed1.png)
