### ISSUE TITLE
Add endodontist specialist

### ISSUE THREAD

**Issue by paragasu** [phisoft/wongandsimdental-web#91]
![image](https://user-images.githubusercontent.com/27353/217591245-94ba19d8-8e91-4389-b7ab-97a38d436111.png)

[20:24, 06/02/2023] Kenneth: add Endodontist Specialist
[20:24, 06/02/2023] Kenneth: under dr tan huan chang name
[20:24, 06/02/2023] Kenneth: Dr Travis Tan Huan Chang

**Comment by norizwana** [comment]
![issue 91 ](https://user-images.githubusercontent.com/124539751/217706210-dcf6fbe6-82f5-43a4-91d1-4c651842b639.png)
#91 Added
![issue 91 web](https://user-images.githubusercontent.com/124539751/217706427-55904cf4-e07d-4c7d-9955-6d0b131887f3.png)
