### ISSUE TITLE
Update operation hours

### ISSUE THREAD

**Issue by paragasu** [phisoft/wongandsimdental-web#98]
![image](https://github.com/phisoft/wongandsimdental-web/assets/27353/c61084ed-a5ec-4bb6-9541-6031d9e578bb)
![image](https://github.com/phisoft/wongandsimdental-web/assets/27353/a9078f49-a3a2-4c96-8f1e-0f05900c75af)

![image](https://github.com/phisoft/wongandsimdental-web/assets/27353/b5f6a69d-02cc-4b1c-afb2-e1062bd6426a)
Pulau Tikus - Monday - Sunday: 0900 - 173

**Comment by Dannytofun** [comment]
![Screenshot 2023-07-13 093301](https://github.com/phisoft/wongandsimdental-web/assets/97335082/2b24a044-57a4-4d19-8be7-b3f33d85e05c)

**Comment by Dannytofun** [comment]
![Screenshot 2023-07-13 100714](https://github.com/phisoft/wongandsimdental-web/assets/97335082/361b81d3-fc38-4430-8013-59b0b255ae43)
